name: continuous dev

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Clone yara-validator
      uses: actions/checkout@v2
      with:
        repository: CIRCL/yara-validator
        path: yara-validator
    - run: python yara-validator/setup.py install

    - name: Pip install
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          flask
          yara-python
          plyara
          pytablewriter[html]
          pyinstaller

    - uses: actions/checkout@v2
    - run: |
        cd YARA-Matches-Correspondance-Array
        pyinstaller -c -F --add-data "static:static" --icon=static/icon.ico -n ymca app.py
        
    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: ymca
        path: dist
