name: continuous dev

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout ymca
      uses: actions/checkout@v2
      
    - name: Install python
      uses: actions/setup-python@v2

    - name: Clone yara-validator
      uses: actions/checkout@v2
      with:
        repository: CIRCL/yara-validator
        path: yara-validator

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        sudo apt install python3-tk -y
        cd yara-validator/
        sudo python setup.py install
        cd ..
        sudo rm -rf yara-validator
        sudo pip install flask yara-python plyara pytablewriter[html] pyinstaller
        sudo pyinstaller -c -F --add-data "static:static" -n ymca app.py
        sudo chmod 777 dist/ymca
 
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: Linux
        files: dist/ymca


  build_windows:
    runs-on: windows-latest
    steps:

    - name: Checkout ymca
      uses: actions/checkout@v2
      
    - name: Install python
      uses: actions/setup-python@v2

    - name: Clone yara-validator
      uses: actions/checkout@v2
      with:
        repository: CIRCL/yara-validator
        path: yara-validator

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install virtualenv
        virtualenv C:\temp\venv
        C:\temp\venv\Scripts\activate.bat
        cd yara-validator/
        python setup.py install
        cd ..
        pip install flask yara-python plyara pytablewriter[html] pyinstaller
        pyinstaller -c -F --add-data "static;static" --icon=static/icon.ico -n ymca.exe app.py
 
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: Windows
        files: dist/ymca.exe
