name: continuous dev venv

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Clone yara-validator
      uses: actions/checkout@v2
      with:
        repository: CIRCL/yara-validator
        path: yara-validator

    - name: Python Instals
      run: |
        pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        python yara-validator/setup.py install
        python -m pip install flask yara-python plyara pytablewriter[html] pyinstaller
        echo "VIRTUAL ENV:" $VIRTUAL_ENV

    - name: checkout ymca
      uses: actions/checkout@v2
      
    - name: bluid ymca      
      run: |
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        pyinstaller -c -F --add-data "static:static" --icon=static/icon.ico -n ymca app.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ymca
        path: dist
