name: continuous dev

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout ymca
      uses: actions/checkout@v2
      
    - name: Install python
      uses: actions/setup-python@v2

    - name: Clone yara-validator
      uses: actions/checkout@v2
      with:
        repository: CIRCL/yara-validator
        path: yara-validator

    - name: Pip Install
      run: |
        pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        sudo python yara-validator/setup.py install
        pip install flask yara-python plyara pytablewriter[html] pyinstaller
        rm -rf yara-validator
        pyinstaller -c -F --add-data "static:static" --icon=static/icon.ico -n ymca app.py
 
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ymca
        path: dist


  build_windows:
    runs-on: windows-latest
    steps:

    - name: Checkout ymca
      uses: actions/checkout@v2
      
    - name: Install python
      uses: actions/setup-python@v2

    - name: Clone yara-validator
      uses: actions/checkout@v2
      with:
        repository: CIRCL/yara-validator
        path: yara-validator

    - name: Pip Install
      run: |
        pip install --upgrade pip
        pip install virtualenv
        virtualenv C:\temp\venv
        C:\temp\venv\Scripts\activate.bat
        python yara-validator/setup.py install
        pip install flask yara-python plyara pytablewriter[html] pyinstaller
        pyinstaller -c -F --add-data "static;static" --icon=static/icon.ico -n ymca.exe app.py
 
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ymca.exe
        path: dist
